name: Tests
on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch: # 手动触发
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'
                type: choice
                options:
                    - info
                    - warning
                    - debug
            tags:
                description: 'Test scenario tags'
                required: false
                type: boolean
            environment:
                description: 'Environment to run tests against'
                type: environment
                required: true

defaults:
    run:
        shell: bash

jobs:
    test:
        name: Test
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest, windows-latest, ubuntu-latest]
                version: [1.1.0, 1.0.0]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup
              id: job
              uses: ./
              with:
                  job-name: other name

            - name: get putput
              run: echo "the job id is ${{ steps.job.outputs }}"
